---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: dockerdemokubapp1
        image: prasadimanjula/dockerdemokub:v2
        ports:
        - containerPort: 80
